100_Doors_Problem/C++/tylerferraro/100doors.cpp, 100_Doors_Problem/Ruby/tylerferraro/100doors.rb
A bit array implementation for the 100 doors algorithm.
=> Added Ruby and C++ implementation of 100 Doors. C++ is using bitset (bit array).

100_Doors_Problem/C#/Davipb/HundredDoors.cs, 100_Doors_Problem/C#/Davipb/HundredDoors_test.cs, 10_Harshad_Number/C#/Davipb/HarshadNumbers.cs, 10_Harshad_Number/C#/Davipb/HarshadNumbers_test.cs, 99_Bottles_Problem/C#/Davipb/BottlesOfBeer.cs, 99_Bottles_Problem/C#/Davipb/BottlesOfBeer_test.cs, Ackermann/C#/Davipb/Ackermann.cs, Ackermann/C#/Davipb/Ackermann_test.cs, Average/C#/Davipb/Averages.cs, Average/C#/Davipb/Averages_test.cs, Bogobogosort/C#/Davipb/BogoBogoSort.cs, Bogobogosort/C#/Davipb/BogoBogoSort_test.cs
Harshad numbers, 99 Bottles of Beer, 100 Doors, Ackermann, Averages and (the most fun to program) BogoBogoSort.
=> Added C# implementation of 6 Algorithms

Einstein_Puzzle/Prolog/warreee/einstein_puzzle.pl, Einstein_Puzzle/Prolog/warreee/einstein_puzzle_test.pl, Einstein_Puzzle/tags
A question about your repo, how do you change the name a folder from Prolog to Prolog/warreee if there is only one subfolder in a language folder?
Thanks
=> Added Prolog Implementation of Einstein Puzzle

99_Bottles_Problem/Python/tylerferraro/99bottles.py, 99_Bottles_Problem/Ruby/tylerferraro/99bottles.rb
Added a ruby implementation for the 99 bottles problem. Also added a different take on the python implementation.
=> Python and Ruby implementation for 99 bottles problem.

Cryptography/C#/Davipb/Cryptography.cs, Cryptography/C#/Davipb/Cryptography_test.cs, Factorial/C#/Davipb/Factorial.cs, Factorial/C#/Davipb/Factorial_test.cs, Fibonacci_series/C#/Davipb/Fibonacci.cs, Fibonacci_series/C#/Davipb/Fibonacci_test.cs, Happy_Number/C#/Davipb/HappyNumbers.cs, Happy_Number/C#/Davipb/HappyNumers_test.cs
Factorial, Cryptography, Fibonacci, and Happy Numbers
=> Added C# implementation of 4 algorithms

Patience_Sort/argvk/PatienceSort.py, Patience_Sort/argvk/PatienceSort_test.py
hey there, here's an implementaion of patience sort in python. 
thanks
=> add patience sort

Floyd_Warshall/Ruby/praserocking/floyd_warshall.rb, Floyd_Warshall/Ruby/praserocking/floyd_warshall_test.rb
Hope this piece of code can help a some ruby programmers.
=> Added floyd_warshall implementation in Ruby

Bubble_Sort/Swift/TarangKhanna/bubble_sort.swift, Bubble_Sort/Swift/TarangKhanna/bubble_sort_test.swift
=> Swift implementation of bubble sort

Euclidean_algorithm/C#/pars87/EuclideanAlgorithm.cs, Euclidean_algorithm/C#/pars87/EuclideanAlgorithmTest.cs
The solution contains an iterative and a recursive solution,
=> Added the solution and test to euclidean algorithm in C#.

Binary_Search/Python/jiang42/binary_search.py, Binary_Search/Python/jiang42/binary_search_test.py
=> fix issue 469

Knuth_Morris_Pratt/Java/darubramha89/KmpSearch.java, Knuth_Morris_Pratt/Java/darubramha89/KmpSearch_test.java, Levenshtein_distance/Java/darubramha89/Levenshtein.java, Levenshtein_distance/Java/darubramha89/Levenshtein_test.java
Added Knuth Morris Prat and Levenshtein Distance Java implementation.
Test cases are in each files main function.
=> Knuth Morris Prat and Levenshtein Java

Average/Java/joshimoo/Average.java, Average/Java/joshimoo/Average_test.java
Additionally  added a unit test for inequalities which must hold, for all average calculations
=> Added Java implementation of Average

10_Harshad_Number/C/jb1717/10_Harshad_Number.c, 10_Harshad_Number/C/jb1717/10_Harshad_Number.h, 10_Harshad_Number/C/jb1717/10_Harshad_Number_test.c
Implementation of Harshad number with the main function for testing.
=> Harshad number C implementation

Decimal_To_Fraction/PHP/jakobhans/DecimalToFraction.php, Decimal_To_Fraction/PHP/jakobhans/DecimalToFraction_test.php
=> Added PHP implementation to convert decimals to fractions

Bogobogosort/PHP/jakobhans/Bogobogosort.php, Bogobogosort/PHP/jakobhans/Bogobogosort_test.php
Had to implement this one... With test file!
=> Implemented Bogobogosort in PHP

Average/PHP/jakobhans/Average.php, Average/PHP/jakobhans/Average_test.php
=> Added PHP file for Average algorithms

.gitignore, Average/Go/roman_kachanovsky/average.go, Average/Go/roman_kachanovsky/average_test.go, Bellman_Ford_Search/Go/roman_kachanovsky/bellman_ford.go, Bellman_Ford_Search/Go/roman_kachanovsky/bellman_ford_test.go, Binary_Search_Tree/Go/roman_kachanovsky/binary_search_tree.go, Binary_Search_Tree/Go/roman_kachanovsky/binary_search_tree_test.go, Cocktail_Sort/Go/roman_kachanovsky/cocktail_sort.go, Cocktail_Sort/Go/roman_kachanovsky/cocktail_sort_test.go, FizzBuzz/Go/roman_kachanovsky/fizz_buzz.go, FizzBuzz/Go/roman_kachanovsky/fizz_buzz_test.go, FizzBuzz/Python/roman_kachanovsky/fizz_buzz.py, FizzBuzz/Python/roman_kachanovsky/fizz_buzz_test.py
Added Go implementations of Average, Bellman-Ford's Search, Binary Search Tree, Cocktail Sort and FizzBuzz (Go and Python ^__^)
=> Average, Bellman-Ford's Search, Binary Search Tree, Cocktail Sort and FizzBuzz with Go

The_Twelve_Days_Of_Xmas/C++/Meyito/Makefile, The_Twelve_Days_Of_Xmas/C++/Meyito/The_twelve_days_of_xmas.cc, The_Twelve_Days_Of_Xmas/C++/Meyito/The_twelve_days_of_xmas.hpp, The_Twelve_Days_Of_Xmas/C++/Meyito/The_twelve_days_of_xmas_test.cc, The_Twelve_Days_Of_Xmas/README.md, The_Twelve_Days_Of_Xmas/tags
Readme and solution for The Twelve Days of Xmas problem added, and tag modified
=> Readme and solution for The Twelve Days of Xmas problem added

N_Queens_Problem/C/RCMainak/nQueen.c, N_Queens_Problem/C/RCMainak/nQueen_test.c
Implementation of N Queen problem in C language.
=> N Queen in C language

Bellman_Ford_Search/C++/shreyans800755/Makefile, Bellman_Ford_Search/C++/shreyans800755/bellman_ford.cpp
Bellman ford algorithm with 2 tests in C++.
1st test with graph not containing negative cycle.
2nd test with graph containing negative cycle.
=> Added C++ implementation for bellman ford algorithm

Palindrome/Python/ivanchoff/palindrome.py
a just added palindrome algortihm in python
=> added palidrome algorithm in python

ROT13_Cipher/Fennel/bb010g/rot13.fnl, ROT13_Cipher/Fennel/bb010g/rot13_test.fnl
[Fennel](https://github.com/bakpakin/Fennel) is a Lisp that compiles to Lua.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kennyledet/algorithm-implementations/527)
=> Implement ROT13_Cipher in Fennel

Palindrome/Racket/Mukesh/palindrome-test.rkt, Palindrome/Racket/Mukesh/palindrome.rkt
Added solution for palindrome problem with separate test file.
=> Palindrome solution in Racket

Palindrome/C++/ivanchoff/palindrome.cc, Palindrome/javascript/ivanchoff/palindrome.js, Palindrome/javascript/ivanchoff/palindrome_test.js
palindrome algorithm in c++ was added
=> Palindrome c++

Decimal_To_Fraction/Python/ivanchoff/decimalToFraction.py, Decimal_To_Fraction/Python/ivanchoff/decimalToFraction_test.py, Palindrome/ruby/ivanchoff/palindrome.rb, Palindrome/ruby/ivanchoff/palindrome_test.rb
added decimal to fraction algorithm in python with tests
=> Decimal to fraction python

Palindrome/ruby/ivanchoff/palindrome.rb, Palindrome/ruby/ivanchoff/palindrome_test.rb
added palindrome algorithm in ruby with test
=> palindrome algorithm implemented in ruby
